Rem change the IP below to your dnsforwarders IP address
set dnsforwarder=10.0.0.4
dnscmd /zoneadd afs.azure.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd agentsvc.azure-automation.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd api.azureml.ms /dsforwarder %dnsforwarder%
dnscmd /zoneadd azconfig.io /dsforwarder %dnsforwarder%
dnscmd /zoneadd azure-automation.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd azure-devices.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd azurecr.io /dsforwarder %dnsforwarder%
dnscmd /zoneadd azurewebsites.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd blob.core.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd cassandra.cosmos.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd cognitiveservices.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd database.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd datafactory.azure.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd dfs.core.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd documents.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd eastus.azmk8s.io /dsforwarder %dnsforwarder%
dnscmd /zoneadd eastus.backup.windowsazure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd eventgrid.azure.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd file.core.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd gremlin.cosmos.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd mariadb.database.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd mongo.cosmos.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd monitor.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd mysql.database.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd notebooks.azure.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd ods.opinsights.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd oms.opinsights.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd postgres.database.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd queue.core.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd redis.cache.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd search.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd service.signalr.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd servicebus.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd table.core.windows.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd table.cosmos.azure.com /dsforwarder %dnsforwarder%
dnscmd /zoneadd vaultcore.azure.net /dsforwarder %dnsforwarder%
dnscmd /zoneadd web.core.windows.net /dsforwarder %dnsforwarder%
